### ISSUE TITLE
Question regarding the code base

### ISSUE THREAD

**Issue by Zainab-Fahim** [poojitagarg/whatsapp-chatbot#1]
Hey, can I know how did you connect the `gsheet_func.py` file with the `app.py` file so that there is a connection between the two, when the user sends in reminders, it automatically updates the googlesheet?
Thank You

**Comment by poojitagarg** [comment]
Hi Zainab! To answer your question, the code line `from gsheet_func import *` in `app.py` is used to import all the functions written in the `gsheet_func.py` file. Hope this helps!

**Comment by Zainab-Fahim** [comment]
Thank You! Yes that helps!
